create week 1 branch for issue 2
the-collab-lab/tcl-16-smart-shopping-list pull request #17
Opened 2021-01-04 17:31 UTC by thekidnamedkd

_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._ 

## Description

## Related Issue

## Acceptance Criteria

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

## Updates

### Before

### After

## Testing Steps / QA Criteria

2021-01-08 20:15 UTC, jessicasalbert approved these changes

2021-01-08 21:25 UTC, Maeesha-Rahman approved these changes

2021-01-10 18:39 UTC, skylerwshaw commented on src/App.js
> +function MenuLink({ label, to, activeWhenExact }) {
I'd recommend setting a default for `activeWhenExact` here so the `useRouteMatch` hook doesn't receive undefined when the optional param isn't sent.

2021-01-10 18:50 UTC, skylerwshaw commented on src/App.js
> +          </Switch>
Not a need for this PR but we may want to consider when a user lands at a route that doesn't match e.g. `http://localhost:3000/SomeOtherView`. http://localhost:3000/SomeOtherView

2021-01-10 18:52 UTC, skylerwshaw requested changes
Though we could reasonably assume `react-router-dom` API will handle sending `exact: undefined`, we should protect against this case. Aside from this small fixup I think the PR is 👌 great.

2021-01-10 19:29 UTC, esolar07 commented
@thekidnamedkd You might need to pull from `main` so you can updated your branch before we merge it

2021-01-10 22:46 UTC, skylerwshaw commented on src/App.js
> +function MenuLink({ label, to, activeWhenExact }) {
```suggestion
function MenuLink({ label, to, activeWhenExact = false }) {
```

I've included a code change you can accept into a commit here for what I was referring to in the comment above.

2021-01-10 22:52 UTC, skylerwshaw approved these changes

2021-01-10 22:53 UTC, merged